### ISSUE TITLE
CI build failing for release/core_1.0rc/1.1

### ISSUE THREAD

**Issue by ThomasKroes** [ManiVaultStudio/HDF5Loader#18]
The CI build for [release/core_1.0rc/1.1](https://github.com/ManiVaultStudio/HDF5Loader/tree/release/core_1.0rc/1.1) is [failing](https://github.com/ManiVaultStudio/HDF5Loader/actions/runs/8122348594/job/22201695465):
```
-- QUERY ERROR RESULT:
items.find(
	{
		"repo":{"$eq" : "conan-local"},
CMake Error at cmake/InstallArtifactoryPackage.cmake:68 (message):
		"name":{"$eq" : "conaninfo.txt"},
  No matching artifactory packages found.  Please check the query.
		"@conan.package.user": {"$eq" : "lkeb"},
Call Stack (most recent call first):
  cmake/InstallArtifactoryPackage.cmake:106 (find_artifactory_package)
		"@conan.package.channel": {"$eq" : "stable"},
		"@conan.package.name": {"$eq" : "hdf5"},
		"@conan.package.version": {"$eq" : "1.14.2"},
		"@conan.settings.os": {"$eq" : "Linux"},
		"@conan.settings.compiler": {"$eq" : "gcc"},
		"@conan.settings.compiler.version": {"$match" : "11*"},
        "@conan.options.with_zlib": {"$match" : "True"}
	}
)
```
, despite the changes below:
```
matrix:
    include:
      - name: Windows-msvc2019
        os: windows-2019
        compiler: msvc-2019
        build-cversion: 16
        build-runtime: MD
        build-config: Release
      - name: Linux_gcc11
        os: ubuntu-22.04
        build-cc: gcc
        build-cxx: g++
        build-compiler: gcc
        build-cversion: 11
        build-config: Release
        build-os: Linux
        build-libcxx: libstdc++
      - name: Macos_xcode13.4
        os: macos-12
        build-compiler: apple-clang
        build-cversion: 13
        build-config: Release
        build-os: Macos
        build-xcode-version: 13.4
        build-libcxx: libc++
```
